#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Thu Sep 15 22:54:44 2011

import wx

# begin wxGlade: extracode
# end wxGlade



class MoveScrnDlg(wx.Dialog):
    def __init__(self, parent, id = -1, collections = []):
        # begin wxGlade: MoveScrnDlg.__init__
        self.parent = parent
        wx.Dialog.__init__(self, self.parent, id, "Move Sccreenshot to:")
        self.collection_choice = wx.Choice(self, -1, choices = collections)
        self.bt_sizer = self.CreateButtonSizer(wx.OK | wx.CANCEL)
        self.__do_layout()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MoveScrnDlg.__do_layout
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        main_sizer.Add(self.collection_choice, 1, wx.ALL|wx.EXPAND, 0)
        main_sizer.Add(self.bt_sizer, 1, wx.ALL|wx.EXPAND, 0)
        self.SetSizer(main_sizer)
        main_sizer.Fit(self)
        self.Layout()
        # end wxGlade

    def ShowModal(self):
        return (wx.Dialog.ShowModal(self), self.collection_choice.GetStringSelection())
# end of class MoveScrnDlg


if __name__ == "__main__":
    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    scrn_move_dlg = MoveScrnDlg(None, -1)
    app.SetTopWindow(scrn_move_dlg)
    scrn_move_dlg.Show()
    app.MainLoop()
